spring:
server:
  servlet:
    context-path: /activiti-app
  port: 9999

#  servlet-path: /mytest/*
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: "*"
spring:
  datasource:
    h2:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=-1
      username: sa
      password:
  aop:
    auto: true
    proxy-target-class: false
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
                cache:
                   use_second_level_cache: false
  output:
    ansi:
      enabled: always
  activiti:
    check-process-definitions: false
  liquibase:
    check-change-log-location: false
    enabled: false


